### ISSUE TITLE
Support SvelteKit SDK Setup

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry-wizard#244]
The Sentry Wizard should support setting up the SvelteKit SDK, similarly to setting up the NextJS SDK.

```[tasklist]
### Tasks

(this is subject to change as I have very little context on the wizard yet)

- [ ] https://github.com/getsentry/sentry-wizard/pull/245
- [ ] https://github.com/getsentry/sentry-wizard/pull/246
- [ ] #249
- [ ] https://github.com/getsentry/sentry-wizard/issues/247
- [ ] #257
- [ ] https://github.com/getsentry/sentry-wizard/pull/259
- [ ] https://github.com/getsentry/sentry-wizard/pull/260
- [ ] https://github.com/getsentry/sentry-wizard/pull/266
- [ ] https://github.com/getsentry/sentry-wizard/pull/267
- [ ] https://github.com/getsentry/sentry-wizard/pull/268
```

ref https://github.com/getsentry/sentry-javascript/issues/6692

**Comment by Lms24** [comment]
Removed the last task of wrapping `load` functions in favour of doing this at build time. We're not going to add a wizard-based solution at this time, as we're still waiting on a `handleLoad` hook for the final solution. The interim solution will be a build-time based auto-instrumentation similar to what we're doing in the NextJs SDK.
