### ISSUE TITLE
[plugin] Wizard for Source Maps Upload Setup 

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#288]
### Problem Statement

I want to add one of the plugins to my project which uses webpack, esbuild, vite, or rollup

Sentry already adds config automatically for some frameworks, by adding or updating via [wizard](https://github.com/getsentry/sentry-wizard) NextJS's custom webpack config in `next.config.js` and for sveltekit in the `vite.config.js`. It is not always possible for all frameworks that a wizard is widely applicable due to lack of strict control in the setup of apps per framework. However maybe it is possible (at least often enough) for certain JS bundlers

**Note:**
This is agnostic to any JS framework being used in an application. It is only related to JS bundlers and similar tools for creating production builds (minified/uglified/etc) of your code.

Examples
`npx @sentry/wizard@latest -i sveltekit` for [SvelteKit](https://docs.sentry.io/platforms/javascript/guides/sveltekit/#install)

`npx @sentry/wizard@latest -i nextjs` for [NextJS](https://docs.sentry.io/platforms/javascript/guides/nextjs/#install)

### Solution Brainstorm

Essentially the wizard has only been for project setup, but we could use it to help with just setting up parts as well. In this case sourcemaps setup with plugin support [webpack](https://github.com/getsentry/sentry-webpack-plugin), [vite, esbuild, and rollup](https://github.com/getsentry/sentry-javascript-bundler-plugins)

User flow: [Option 2 Wizard Setup](https://www.figma.com/file/NZX0hEUtVH9FLcJRm8gvkg/Source-Maps-%2B-New-Auth-Token?type=design&node-id=416-1618&mode=design&t=a77n6EpvhQyXx4m7-0)

### Requirements

- user receives all keys, tokens, and variables required to create releases and upload source maps to sentry
- either to existing .env file(s) or new if not existing
- user has scripts which run sentry-cli commands with all proper inputs (these could be provided already by bundlers)
- user receives log statements which simply explain what has been done & what they should do example: yarn run build
- user receives log statements which simple state what was attempted and failed, then what they should do next (docs)

```[tasklist]
### Tasks
- [ ] Create `.env` file with SENTRY_AUTH_TOKEN, SENTRY_ORG, SENTRY_PROJECT
- [ ] wizard allows a CLI command which checks for known JS bundlers `-plugin`
- [ ] checks for known config files `config.webpack`, `config.vite`, `config.rollup` etc
- [ ] if no file because all bundlers (webpack) do not require a conifg files check if it is in dependencies or other signifiers
- [ ] if none are there, then wizard automatically adds
- [ ] if no indication of any known JS bundler is there direct then via link to most relevant source maps docs
- [ ] updates existing config files based on logic associated with own respective arguments
- [ ] vite wizard `-vite` if user knows to use directly vite
- [ ] webpack wizard `-webpack` if user knows to use directly webpack
- [ ] rollup wizard `-rollup` if user knows to use directly rollup
- [ ] Confim if esbuild is really not possible
- [ ] if the wizard runs into a problem it can: 1) fail out or 2) attempt to create a duplicate file with the config
- [ ] (stretch) detect why update/merge did not work and inform the user
- [ ] (stretch) detect a known bundler where we do not have a plugin but can link to docs with explicit instructions
```

Imagine if you will . . . ⭐ 
`npx @Sentry/wizard@latest -i plugin`

**Comment by Lms24** [comment]
A few ideas/thoughts about CLI args/invocation:

```bash
# command for auto detection of used tool + setup of the detected tool
npx @Sentry/wizard@latest -i sourcemaps

# command for setup of vite plugin
npx @Sentry/wizard@latest -i sourcemaps --tool vite

# command for setup of rollup plugin
npx @Sentry/wizard@latest -i sourcemaps --tool rollup

# command for setup of plain Sentry CLI script
npx @Sentry/wizard@latest -i sourcemaps --tool cli

# Idea: One of these commands could list the available tool options
npx @Sentry/wizard@latest -i sourcemaps --help
npx @Sentry/wizard@latest -i sourcemaps --tool
```

**Comment by Lms24** [comment]
Notes from kick-off meeting:

First iteration:
1. start w/ `-i sourcemaps`
2. "Login flow" <-- this is universal to all tools/bundlers
  * Ask for self-hosted (we already do that) URL
  * `.sentryclirc` holds only auth token (we already do that)
  * adjust `.gitgnore` (we already do that)
  * rest of config (org, project, url) goes into bundler config or CLI script args (instead of `sentry.properties`)
4. Select bundler
5. Print copy paste snippets for plugin config to console

Priorities:
1. vite, webpack, CLI
2. rollup, esbuild

How to invoke CLI script:
- if `build && !postbuild` -> add as `postbuild`
- otherwise, add as e.g. `sentry-ci`

We'll open an epic to track all wizard-related development work

**Comment by ale-cota** [comment]
Closing this one, as the work is being done in: https://github.com/getsentry/team-sdks/issues/16
