### ISSUE TITLE
[sentry-cli] Wizard for Source Maps Setup

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#289]
### Problem Statement

I want to create releases and upload source maps to sentry with new builds, locally and in CI, so I can track issues and performance across releases.

Sentry already adds config automatically for some frameworks, by adding or updating via [wizard](https://github.com/getsentry/sentry-wizard) NextJS's custom webpack config in `next.config.js` and for sveltekit in the `vite.config.js`. It is not always possible for all frameworks that a wizard is widely applicable due to lack of strict control in the setup of apps per framework. However maybe it is possible (at least often enough) for certain JS bundlers

This feature should work to handle all scenarios not covered by bundler-plugins or 

Examples
`npx @sentry/wizard@latest -i sveltekit` for [SvelteKit](https://docs.sentry.io/platforms/javascript/guides/sveltekit/#install)

`npx @sentry/wizard@latest -i nextjs` for [NextJS](https://docs.sentry.io/platforms/javascript/guides/nextjs/#install)

### Solution Brainstorm

Essentially the "wizard" has only been for project setup, but we could use it to help with just setting up parts as well. In this case release creation and source maps upload with sentry-cli

User flow: [Option 2 Wizard Setup](https://www.figma.com/file/NZX0hEUtVH9FLcJRm8gvkg/Source-Maps-%2B-New-Auth-Token?type=design&node-id=416-1618&mode=design&t=a77n6EpvhQyXx4m7-0)

### Requirements

- user receives all keys, tokens, and variables required to create releases and upload source maps to sentry
  - either to existing .env file(s) or new if not existing
- user has scripts which run sentry-cli commands with all proper inputs
- user receives log statements which simply explain what has been done & what they should do example: `yarn run build`
- user receives log statements which simple state what was attempted and failed, then what they should do next (docs)
  - including logs, of files updated successfully, or copies created and you need merge etc

```[tasklist]
### Tasks
- [ ] wizard allows a CLI command which checks for known JS bundlers `-plugin`
- [ ] wizard create .env file with `SENTRY_AUTH_TOKEN`, `SENTRY_ORG`, `SENTRY_PROJECT`
- [ ] wizard updates package scripts JSON to run sentry-cli commands
- [ ] new script (tbc new or existing: may also be different scenarios to consider) should attempt to create a release upon running and upload source maps
- [ ] `sentry-cli sourcemaps inject /path/to/directory`
- [ ] `sentry-cli sourcemaps upload /path/to/directory`
- [ ] arguably optional: `sentry-cli sourcemaps upload --release=<release_name> /path/to/directory`
- [ ] arguably optional:  `sentry-cli sourcemaps upload --release=<release_name> --dist=<dist_name> /path/to/directory`
```

```[tasklist]
### Situations to consider
- [ ] Check for [Typescript](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/typescript/) (and no other bundler or compiler etc)
- [ ] Check for presence of [Uglify](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/uglifyjs/)
- [ ] Check for presence of [SystemJS](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/systemjs/?original_referrer=https%3A%2F%2Fwww.google.com%2F)
- [ ] if more than one option available should the wizard prompt the user what they would like? Should our wizard take an opinion at times of what is preferred
- [ ] Set up Sentry CLI as described above and potentially including extra config or scripts as defined in our guides

```

### Open questions:
We have issues with users uploading too many bundles to the same release(s) which is then possibly used across projects. This creates expensive overheads in symbolication to find the correct files to connect with stack traces. To resolve this we ideally should attempt to set releases for the users, and `-dist` when it makes sense. This can allow for our storage and services to scale much better.
- [-dist](https://docs.sentry.io/product/cli/releases/?original_referrer=https%3A%2F%2Fwww.google.com%2F#:~:text=the%20upload%20command%3A-,%2D%2Ddist,-Sets%20the%20distribution) should we consider ways to better set unique and meaningful -dist for source maps upload?
- [creating releases](https://docs.sentry.io/product/cli/releases/?original_referrer=https%3A%2F%2Fwww.google.com%2F#creating-releases)
  - detecting unique meaningful releases dynamically: investigation into methods employed by different SDKs
  - https://develop-git-smeubank-detect-release.sentry.dev/sdk/event-payloads/release/

Imagine if you will . . . ⭐ 
`npx @Sentry/wizard@latest -i sourcemaps`

**Comment by Lms24** [comment]
@smeubank can we close this issue? I think the CLI tasks are basically done and the stretch goals around uglify/systemjs are mentioned in https://github.com/getsentry/team-sdks/issues/16
