### ISSUE TITLE
iOS cli-wizard

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#330]
### Background:

Success rates for developers creating iOS projects and sending events, are low in comparison to other platforms. We want to ship a number of improvements to address this and try to help iOS devs navigate setting up their iOS apps with Sentry. This issue will focus on shipping a cli-wizard

### Solution Proposal:

At first this wizard is really only intended for setting up iOS apps which do not have any Sentry configuration yet, However the wizard should recognize if there is existing config, in the future it may be desirable to update existing. For now we will ignore this complexity.

Goal: Make it exceedingly easy for users to get started with Sentry on iOS

`brew @sentry/wizard@latest -i ios`

**Login:**
- add a one line wizard command to setup an iOS application with Sentry SDK and potentially build tool plugins

**Install:**
- Wizard would need to have logic to detect which build of the sentry-cocoa SDK is needed for the users platform
- if cannot auto-detect then prompt user to select

**Configure:**
- inject needed config options
- SDK init should include GA top product enabled options (Errors & Performance)
  - potebtially profiling

**Verify:**
- [nice to have] an error page equivalent to easily allow the user to test the setup

**Build tooling:**
- xCode
- FastLane
- sentry-cli

### Tasks

```[tasklist]
### Tasks
- [x] https://github.com/getsentry/sentry-wizard/pull/334
- [ ] https://github.com/getsentry/sentry-wizard/pull/350
- [ ] https://github.com/getsentry/sentry-wizard/pull/356
- [ ] https://github.com/getsentry/sentry-wizard/issues/343
```

#### Requirements

- user can run a one liner in their terminal to trigger flow
- User prompted to login or create account
  - existing get's list of existing projects
  - create back to terminal with created project in list   
- user receives all keys, tokens, and variables required to create releases and upload source maps to sentry
- user app is injected with a script which run sentry-cli commands with all proper inputs (these could be provided already by bundlers)
- user receives log statements which simply state what was attempted (succeeded and/or failed), then what they should do next (docs, manual merge, copy/paste, yarn run build)

### Reference:

- react-native wizard: `npx @sentry/wizard@latest -s -i reactNative`
  - https://github.com/getsentry/sentry-wizard/issues/280
- NextJS: `npx @sentry/wizard@latest -i nextjs`
- SvelteKit: `npx @sentry/wizard@latest -i sveltekit`
- Delivery approach for source maps for JS: https://github.com/getsentry/team-sdks/issues/16
- https://github.com/getsentry/team-mobile/issues/26

**Comment by kahest** [comment]
- [ ] [basic support with SPM](https://github.com/getsentry/sentry-wizard/pull/334)
- [ ] [CocoaPods support](https://github.com/getsentry/sentry-wizard/pull/350)
- [ ] Fastlane support

**Comment by brustolin** [comment]
I believe we have a good first version.
This is focused on iOS only, if we need to support macOS some adjustments are required.
