### ISSUE TITLE
Add Wizard for Angular

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry-wizard#672]
We want to add a wizard flow for Angular.

```[tasklist]
### Tasks
- [x] Add menu option and install SDK - #765
- [x] Add Sentry setup in `main.ts` - https://github.com/getsentry/sentry-wizard/pull/768
- [x] Add Sentry setup in App Config - https://github.com/getsentry/sentry-wizard/pull/769
- [x] configure source map upload - https://github.com/getsentry/sentry-wizard/pull/770
- [x] Add e2e test app(s) - https://github.com/getsentry/sentry-wizard/pull/780
- [ ] https://github.com/getsentry/sentry-wizard/pull/953
- [ ] https://github.com/getsentry/sentry-wizard/pull/963
- [ ] https://github.com/getsentry/sentry-docs/pull/13472
```
